// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/defectos_queso.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class DefectoQueso {
  final String id;
  final String nombre;
  final String tipo;
  final String causa_posible;
  final String severidad;
  final String requiere_accion;
  final String visible_ia;
  final String revisado_por;

  const DefectoQueso({
    required this.id,
    required this.nombre,
    required this.tipo,
    required this.causa_posible,
    required this.severidad,
    required this.requiere_accion,
    required this.visible_ia,
    required this.revisado_por,
  });

  factory DefectoQueso.fromMap(Map<String, String> m) => DefectoQueso(
    id: m['id'] ?? '',
    nombre: m['nombre'] ?? '',
    tipo: m['tipo'] ?? '',
    causa_posible: m['causa_posible'] ?? '',
    severidad: m['severidad'] ?? '',
    requiere_accion: m['requiere_accion'] ?? '',
    visible_ia: m['visible_ia'] ?? '',
    revisado_por: m['revisado_por'] ?? '',
  );

  Map<String, String> toMap() => {
    'id': id,
    'nombre': nombre,
    'tipo': tipo,
    'causa_posible': causa_posible,
    'severidad': severidad,
    'requiere_accion': requiere_accion,
    'visible_ia': visible_ia,
    'revisado_por': revisado_por,
  };
}

const List<DefectoQueso> todosDefectoQuesos = [
    DefectoQueso(id: 'ojos_excesivos', nombre: 'Ojos excesivos / mecánica', tipo: 'textura', causa_posible: 'Fermentos contaminantes', severidad: 'media', requiere_accion: 'limpieza_profundidad', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'ojos_insuficientes', nombre: 'Falta de ojos', tipo: 'textura', causa_posible: 'Fermento inadecuado', severidad: 'media', requiere_accion: 'revisar_fermento', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'ojos_irregulares', nombre: 'Ojos irregulares', tipo: 'textura', causa_posible: 'Contaminación por coliformes', severidad: 'alta', requiere_accion: 'analitica', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'hendiduras', nombre: 'Hendiduras internas', tipo: 'textura', causa_posible: 'Problema de acidificación', severidad: 'media', requiere_accion: 'revisar_ph', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'harinosa', nombre: 'Textura harinosa', tipo: 'textura', causa_posible: 'Exceso de acidez', severidad: 'media', requiere_accion: 'revisar_ph', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'gomosa', nombre: 'Textura gomosa', tipo: 'textura', causa_posible: 'Baja acidez / pH alto', severidad: 'media', requiere_accion: 'revisar_ph', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'pegajosa', nombre: 'Textura pegajosa', tipo: 'textura', causa_posible: 'Fermentación incompleta', severidad: 'alta', requiere_accion: 'revisar_proceso', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'grietas_corteza', nombre: 'Grietas en corteza', tipo: 'corteza', causa_posible: 'S eco excesivo', severidad: 'media', requiere_accion: 'control_hr', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'moho_superficial', nombre: 'Moho superficial no deseado', tipo: 'corteza', causa_posible: 'Contaminación ambiental', severidad: 'alta', requiere_accion: 'limpieza_cava', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'acaros', nombre: 'Ácaros en corteza', tipo: 'corteza', causa_posible: 'Falta de limpieza / HR alta', severidad: 'alta', requiere_accion: 'tratamiento_acaricida', visible_ia: 'NO', revisado_por: ''),
    DefectoQueso(id: 'separacion_corteza', nombre: 'Separación corteza-pasta', tipo: 'corteza', causa_posible: 'S eco rápido / HR baja', severidad: 'media', requiere_accion: 'control_hr', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'color_anormal', nombre: 'Color anormal de la pasta', tipo: 'color', causa_posible: 'Alimentación animal / aditivos', severidad: 'baja', requiere_accion: 'revisar_leche', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'manchas_grises', nombre: 'Manchas grises en pasta', tipo: 'color', causa_posible: 'Contaminación metálica', severidad: 'alta', requiere_accion: 'revisar_utensilios', visible_ia: 'SÍ', revisado_por: ''),
    DefectoQueso(id: 'amargor', nombre: 'Sabor amargo', tipo: 'sabor', causa_posible: 'Fermento inadecuado / sal', severidad: 'alta', requiere_accion: 'revisar_fermento', visible_ia: 'NO', revisado_por: ''),
    DefectoQueso(id: 'acido', nombre: 'Sabor excesivamente ácido', tipo: 'sabor', causa_posible: 'Exceso de acidificación', severidad: 'media', requiere_accion: 'revisar_proceso', visible_ia: 'NO', revisado_por: ''),
    DefectoQueso(id: 'picante_anormal', nombre: 'Picante anormal', tipo: 'sabor', causa_posible: 'Contaminación / mala leche', severidad: 'alta', requiere_accion: 'analitica', visible_ia: 'NO', revisado_por: ''),
    DefectoQueso(id: 'hinchazon_precoz', nombre: 'Hinchazón precoz', tipo: 'hinchazon', causa_posible: 'Contaminación por clostridios', severidad: 'alta', requiere_accion: 'analitica', visible_ia: 'NO', revisado_por: ''),
    DefectoQueso(id: 'hinchazon_tardia', nombre: 'Hinchazón tardía', tipo: 'hinchazon', causa_posible: 'Clostridios butíricos en leche', severidad: 'alta', requiere_accion: 'analitica_leche', visible_ia: 'SÍ', revisado_por: ''),
];
