// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/do_quesos.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class DoQueso {
  final String id;
  final String nombre;
  final String tipo;
  final String zona_geografica;
  final String razas_permitidas;
  final String tipo_leche;
  final String coccion;
  final String curacion_minima_dias;
  final String ahumado_permitido;
  final String organismo_control;
  final String web;
  final String revisado_por;

  const DoQueso({
    required this.id,
    required this.nombre,
    required this.tipo,
    required this.zona_geografica,
    required this.razas_permitidas,
    required this.tipo_leche,
    required this.coccion,
    required this.curacion_minima_dias,
    required this.ahumado_permitido,
    required this.organismo_control,
    required this.web,
    required this.revisado_por,
  });

  factory DoQueso.fromMap(Map<String, String> m) => DoQueso(
    id: m['id'] ?? '',
    nombre: m['nombre'] ?? '',
    tipo: m['tipo'] ?? '',
    zona_geografica: m['zona_geografica'] ?? '',
    razas_permitidas: m['razas_permitidas'] ?? '',
    tipo_leche: m['tipo_leche'] ?? '',
    coccion: m['coccion'] ?? '',
    curacion_minima_dias: m['curacion_minima_dias'] ?? '',
    ahumado_permitido: m['ahumado_permitido'] ?? '',
    organismo_control: m['organismo_control'] ?? '',
    web: m['web'] ?? '',
    revisado_por: m['revisado_por'] ?? '',
  );

  Map<String, String> toMap() => {
    'id': id,
    'nombre': nombre,
    'tipo': tipo,
    'zona_geografica': zona_geografica,
    'razas_permitidas': razas_permitidas,
    'tipo_leche': tipo_leche,
    'coccion': coccion,
    'curacion_minima_dias': curacion_minima_dias,
    'ahumado_permitido': ahumado_permitido,
    'organismo_control': organismo_control,
    'web': web,
    'revisado_por': revisado_por,
  };
}

const List<DoQueso> todosDoQuesos = [
    DoQueso(id: 'idiazabal', nombre: 'Idiazábal', tipo: 'DOP', zona_geografica: 'País Vasco y Navarra (excepto Roncal)', razas_permitidas: 'latxa;carranzana', tipo_leche: 'oveja', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'SÍ', organismo_control: 'Consejo Regulador DOP Idiazabal', web: 'doidiazabal.com', revisado_por: ''),
    DoQueso(id: 'manchego', nombre: 'Manchego', tipo: 'DOP', zona_geografica: 'Castilla-La Mancha', razas_permitidas: 'manchega', tipo_leche: 'oveja', coccion: 'cruda o pasteurizada', curacion_minima_dias: '30', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Manchego', web: 'doqmanchego.es', revisado_por: ''),
    DoQueso(id: 'roncal', nombre: 'Roncal', tipo: 'DOP', zona_geografica: 'Valle del Roncal (Navarra)', razas_permitidas: 'latxa', tipo_leche: 'oveja', coccion: 'cruda', curacion_minima_dias: '120', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Roncal', web: '', revisado_por: ''),
    DoQueso(id: 'cabrales', nombre: 'Cabrales', tipo: 'DOP', zona_geografica: 'Asturias', razas_permitidas: 'frisona;asturiana', tipo_leche: 'mezcla (vaca/oveja/cabra)', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Cabrales', web: '', revisado_por: ''),
    DoQueso(id: 'mahon', nombre: 'Mahón-Menorca', tipo: 'DOP', zona_geografica: 'Menorca', razas_permitidas: 'frisona', tipo_leche: 'vaca', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Mahón', web: '', revisado_por: ''),
    DoQueso(id: 'gamoniu', nombre: 'Gamonéu', tipo: 'DOP', zona_geografica: 'Asturias', razas_permitidas: 'frisona;asturiana', tipo_leche: 'mezcla (vaca/oveja/cabra)', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Gamonéu', web: '', revisado_por: ''),
    DoQueso(id: 'torta_casar', nombre: 'Torta del Casar', tipo: 'DOP', zona_geografica: 'Extremadura', razas_permitidas: 'merina', tipo_leche: 'oveja', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Torta del Casar', web: 'tortadelcasar.org', revisado_por: ''),
    DoQueso(id: 'zamorano', nombre: 'Zamorano', tipo: 'DOP', zona_geografica: 'Castilla y León', razas_permitidas: 'churra;castellana', tipo_leche: 'oveja', coccion: 'cruda', curacion_minima_dias: '100', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Zamorano', web: '', revisado_por: ''),
    DoQueso(id: 'tetilla', nombre: 'Tetilla', tipo: 'DOP', zona_geografica: 'Galicia', razas_permitidas: 'frisona;rubia_gallega', tipo_leche: 'vaca', coccion: 'pasteurizada', curacion_minima_dias: '7', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Tetilla', web: '', revisado_por: ''),
    DoQueso(id: 'arzua_ulloa', nombre: 'Arzúa-Ulloa', tipo: 'DOP', zona_geografica: 'Galicia', razas_permitidas: 'frisona;rubia_gallega', tipo_leche: 'vaca', coccion: 'pasteurizada', curacion_minima_dias: '7', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Arzúa-Ulloa', web: '', revisado_por: ''),
    DoQueso(id: 'ibores', nombre: 'Ibores', tipo: 'DOP', zona_geografica: 'Extremadura', razas_permitidas: 'retinta;verata;serrana', tipo_leche: 'cabra', coccion: 'cruda', curacion_minima_dias: '30', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Ibores', web: '', revisado_por: ''),
    DoQueso(id: 'majorero', nombre: 'Majorero', tipo: 'DOP', zona_geografica: 'Fuerteventura', razas_permitidas: 'majorera', tipo_leche: 'cabra', coccion: 'cruda o pasteurizada', curacion_minima_dias: '15', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Majorero', web: '', revisado_por: ''),
    DoQueso(id: 'palmero', nombre: 'Queso Palmero', tipo: 'DOP', zona_geografica: 'La Palma', razas_permitidas: 'palmera', tipo_leche: 'cabra', coccion: 'cruda', curacion_minima_dias: '15', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Palmero', web: '', revisado_por: ''),
    DoQueso(id: 'serena', nombre: 'Queso de la Serena', tipo: 'DOP', zona_geografica: 'Extremadura', razas_permitidas: 'merina', tipo_leche: 'oveja', coccion: 'cruda', curacion_minima_dias: '60', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Serena', web: '', revisado_por: ''),
    DoQueso(id: 'cabrero', nombre: 'Camerano', tipo: 'DOP', zona_geografica: 'La Rioja', razas_permitidas: '', tipo_leche: 'cabra', coccion: '', curacion_minima_dias: '30', ahumado_permitido: 'NO', organismo_control: 'Consejo Regulador DOP Camerano', web: '', revisado_por: ''),
];
