// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/parametros_analitica.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class ParametroAnalitica {
  final String id;
  final String nombre;
  final String unidad;
  final String tipo;
  final String limite_legal;
  final String metodo;
  final String revisado_por;

  const ParametroAnalitica({
    required this.id,
    required this.nombre,
    required this.unidad,
    required this.tipo,
    required this.limite_legal,
    required this.metodo,
    required this.revisado_por,
  });

  factory ParametroAnalitica.fromMap(Map<String, String> m) => ParametroAnalitica(
    id: m['id'] ?? '',
    nombre: m['nombre'] ?? '',
    unidad: m['unidad'] ?? '',
    tipo: m['tipo'] ?? '',
    limite_legal: m['limite_legal'] ?? '',
    metodo: m['metodo'] ?? '',
    revisado_por: m['revisado_por'] ?? '',
  );

  Map<String, String> toMap() => {
    'id': id,
    'nombre': nombre,
    'unidad': unidad,
    'tipo': tipo,
    'limite_legal': limite_legal,
    'metodo': metodo,
    'revisado_por': revisado_por,
  };
}

const List<ParametroAnalitica> todosParametroAnaliticas = [
    ParametroAnalitica(id: 'escherichia_coli', nombre: 'Escherichia coli', unidad: 'ufc/g', tipo: 'microbiologico', limite_legal: '10', metodo: 'RD 3484/2000', revisado_por: ''),
    ParametroAnalitica(id: 'listeria', nombre: 'Listeria monocytogenes', unidad: 'ausencia/25g', tipo: 'microbiologico', limite_legal: 'ausencia', metodo: 'RGCE 2073/2005', revisado_por: ''),
    ParametroAnalitica(id: 'salmonella', nombre: 'Salmonella spp.', unidad: 'ausencia/25g', tipo: 'microbiologico', limite_legal: 'ausencia', metodo: 'RGCE 2073/2005', revisado_por: ''),
    ParametroAnalitica(id: 'stafilococos', nombre: 'Staphylococcus aureus coagulasa+', unidad: 'ufc/g', tipo: 'microbiologico', limite_legal: '100', metodo: 'RGCE 2073/2005', revisado_por: ''),
    ParametroAnalitica(id: 'enterobacterias', nombre: 'Enterobacterias totales', unidad: 'ufc/g', tipo: 'microbiologico', limite_legal: '1000', metodo: 'ISO 21528-2', revisado_por: ''),
    ParametroAnalitica(id: 'hongos_levaduras', nombre: 'Hongos y levaduras', unidad: 'ufc/g', tipo: 'microbiologico', limite_legal: '', metodo: 'ISO 21527', revisado_por: ''),
    ParametroAnalitica(id: 'clostridios_sulfito', nombre: 'Clostridios sulfito-reductores', unidad: 'ufc/g', tipo: 'microbiologico', limite_legal: '100', metodo: 'ISO 15213', revisado_por: ''),
    ParametroAnalitica(id: 'ph', nombre: 'pH', unidad: 'pH', tipo: 'fisico_quimico', limite_legal: '4.8-6.5', metodo: 'potenciometro', revisado_por: ''),
    ParametroAnalitica(id: 'humedad', nombre: 'Humedad', unidad: '%', tipo: 'fisico_quimico', limite_legal: '', metodo: 'estufa', revisado_por: ''),
    ParametroAnalitica(id: 'extracto_seco', nombre: 'Extracto seco', unidad: '%', tipo: 'fisico_quimico', limite_legal: '', metodo: 'estufa', revisado_por: ''),
    ParametroAnalitica(id: 'grasa', nombre: 'Grasa / extracto graso', unidad: '%', tipo: 'fisico_quimico', limite_legal: '', metodo: 'butirometrico', revisado_por: ''),
    ParametroAnalitica(id: 'proteina', nombre: 'Proteína', unidad: '%', tipo: 'fisico_quimico', limite_legal: '', metodo: 'Kjeldahl', revisado_por: ''),
    ParametroAnalitica(id: 'sal', nombre: 'Sal / cloruro sódico', unidad: '%', tipo: 'fisico_quimico', limite_legal: '', metodo: 'Mohr', revisado_por: ''),
    ParametroAnalitica(id: 'actividad_agua', nombre: 'Actividad de agua (aw)', unidad: '-', tipo: 'fisico_quimico', limite_legal: '', metodo: 'higrometro', revisado_por: ''),
];
