// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/razas_lecheras.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class RazaLechera {
  final String id;
  final String nombre_comun;
  final String nombre_cientifico;
  final String tipo_leche;
  final String zona_originaria;
  final String do_asociada;
  final String revisado_por;

  const RazaLechera({
    required this.id,
    required this.nombre_comun,
    required this.nombre_cientifico,
    required this.tipo_leche,
    required this.zona_originaria,
    required this.do_asociada,
    required this.revisado_por,
  });

  factory RazaLechera.fromMap(Map<String, String> m) => RazaLechera(
    id: m['id'] ?? '',
    nombre_comun: m['nombre_comun'] ?? '',
    nombre_cientifico: m['nombre_cientifico'] ?? '',
    tipo_leche: m['tipo_leche'] ?? '',
    zona_originaria: m['zona_originaria'] ?? '',
    do_asociada: m['do_asociada'] ?? '',
    revisado_por: m['revisado_por'] ?? '',
  );

  Map<String, String> toMap() => {
    'id': id,
    'nombre_comun': nombre_comun,
    'nombre_cientifico': nombre_cientifico,
    'tipo_leche': tipo_leche,
    'zona_originaria': zona_originaria,
    'do_asociada': do_asociada,
    'revisado_por': revisado_por,
  };
}

const List<RazaLechera> todosRazaLecheras = [
    RazaLechera(id: 'latxa', nombre_comun: 'Latxa', nombre_cientifico: 'Apis mellifera iberica (oveja)', tipo_leche: 'oveja', zona_originaria: 'Pirineo vasco-navarro', do_asociada: 'idiazabal;roncal', revisado_por: ''),
    RazaLechera(id: 'carranzana', nombre_comun: 'Carranzana', nombre_cientifico: 'ovis aries (carranzana)', tipo_leche: 'oveja', zona_originaria: 'País Vasco', do_asociada: 'idiazabal', revisado_por: ''),
    RazaLechera(id: 'manchega', nombre_comun: 'Manchega', nombre_cientifico: 'ovis aries (manchega)', tipo_leche: 'oveja', zona_originaria: 'Castilla-La Mancha', do_asociada: 'manchego', revisado_por: ''),
    RazaLechera(id: 'merina', nombre_comun: 'Merina', nombre_cientifico: 'ovis aries (merina)', tipo_leche: 'oveja', zona_originaria: 'Extremadura', do_asociada: 'serena;zamorano', revisado_por: ''),
    RazaLechera(id: 'churra', nombre_comun: 'Churra', nombre_cientifico: 'ovis aries (churra)', tipo_leche: 'oveja', zona_originaria: 'Castilla y León', do_asociada: 'zamorano', revisado_por: ''),
    RazaLechera(id: 'murciano_granadina', nombre_comun: 'Murciano-Granadina', nombre_cientifico: 'capra hircus (murciano)', tipo_leche: 'cabra', zona_originaria: 'Murcia', do_asociada: 'murcia;murcia_vino', revisado_por: ''),
    RazaLechera(id: 'majorera', nombre_comun: 'Majorera', nombre_cientifico: 'capra hircus (majorera)', tipo_leche: 'cabra', zona_originaria: 'Fuerteventura', do_asociada: 'majorero', revisado_por: ''),
    RazaLechera(id: 'palmera', nombre_comun: 'Palmera', nombre_cientifico: 'capra hircus (palmera)', tipo_leche: 'cabra', zona_originaria: 'La Palma', do_asociada: 'palmero', revisado_por: ''),
    RazaLechera(id: 'ibicenca', nombre_comun: 'Ibicenca', nombre_cientifico: 'capra hircus (ibicenca)', tipo_leche: 'cabra', zona_originaria: 'Baleares', do_asociada: '', revisado_por: ''),
    RazaLechera(id: 'frisona', nombre_comun: 'Frisona / Holstein', nombre_cientifico: 'bos taurus (frison)', tipo_leche: 'vaca', zona_originaria: 'Europa', do_asociada: 'tetilla;arzua_ulloa;mahon', revisado_por: ''),
    RazaLechera(id: 'asturiana', nombre_comun: 'Asturiana de los Valles', nombre_cientifico: 'bos taurus (asturiana)', tipo_leche: 'vaca', zona_originaria: 'Asturias', do_asociada: 'cabrales;gamoneu;casin', revisado_por: ''),
    RazaLechera(id: 'alpine', nombre_comun: 'Alpina', nombre_cientifico: 'bos taurus (alpina)', tipo_leche: 'vaca', zona_originaria: 'Alpes', do_asociada: '', revisado_por: ''),
    RazaLechera(id: 'rubia_gallega', nombre_comun: 'Rubia Gallega', nombre_cientifico: 'bos taurus (rubia)', tipo_leche: 'vaca', zona_originaria: 'Galicia', do_asociada: 'tetilla', revisado_por: ''),
    RazaLechera(id: 'retinta', nombre_comun: 'Retinta', nombre_cientifico: 'capra hircus (retinta)', tipo_leche: 'cabra', zona_originaria: 'Extremadura', do_asociada: 'ibores', revisado_por: ''),
    RazaLechera(id: 'verata', nombre_comun: 'Verata', nombre_cientifico: 'capra hircus (verata)', tipo_leche: 'cabra', zona_originaria: 'Extremadura', do_asociada: 'ibores', revisado_por: ''),
    RazaLechera(id: 'pirenaica', nombre_comun: 'Pirenaica', nombre_cientifico: 'bos taurus (pirenaica)', tipo_leche: 'vaca', zona_originaria: 'Pirineos', do_asociada: '', revisado_por: ''),
    RazaLechera(id: 'serrana', nombre_comun: 'Serrana', nombre_cientifico: 'capra hircus (serrana)', tipo_leche: 'cabra', zona_originaria: 'Extremadura', do_asociada: 'ibores;serena', revisado_por: ''),
];
