// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/tipos_queso.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class TipoQueso {
  final String id;
  final String nombre;
  final String categoria;
  final String do_id;
  final String curacion_minima_dias;
  final String descripcion;
  final String revisado_por;

  const TipoQueso({
    required this.id,
    required this.nombre,
    required this.categoria,
    required this.do_id,
    required this.curacion_minima_dias,
    required this.descripcion,
    required this.revisado_por,
  });

  factory TipoQueso.fromMap(Map<String, String> m) => TipoQueso(
    id: m['id'] ?? '',
    nombre: m['nombre'] ?? '',
    categoria: m['categoria'] ?? '',
    do_id: m['do_id'] ?? '',
    curacion_minima_dias: m['curacion_minima_dias'] ?? '',
    descripcion: m['descripcion'] ?? '',
    revisado_por: m['revisado_por'] ?? '',
  );

  Map<String, String> toMap() => {
    'id': id,
    'nombre': nombre,
    'categoria': categoria,
    'do_id': do_id,
    'curacion_minima_dias': curacion_minima_dias,
    'descripcion': descripcion,
    'revisado_por': revisado_por,
  };
}

const List<TipoQueso> todosTipoQuesos = [
    TipoQueso(id: 'fresco', nombre: 'Fresco', categoria: 'fresco', do_id: '', curacion_minima_dias: '0', descripcion: 'Queso sin curar de pasta blanda y alto contenido en humedad', revisado_por: ''),
    TipoQueso(id: 'semicurado', nombre: 'Semicurado', categoria: 'curado', do_id: '', curacion_minima_dias: '30', descripcion: 'Queso con curación entre 30 y 60 días', revisado_por: ''),
    TipoQueso(id: 'curado', nombre: 'Curado', categoria: 'curado', do_id: '', curacion_minima_dias: '60', descripcion: 'Curado entre 60 y 120 días', revisado_por: ''),
    TipoQueso(id: 'viejo', nombre: 'Viejo / Añejo', categoria: 'curado', do_id: '', curacion_minima_dias: '120', descripcion: 'Mínimo 4 meses de curación', revisado_por: ''),
    TipoQueso(id: 'idiazabal_semicurado', nombre: 'Idiazábal semicurado', categoria: 'do_curado', do_id: 'idiazabal', curacion_minima_dias: '60', descripcion: 'DO Idiazábal con curación media', revisado_por: ''),
    TipoQueso(id: 'idiazabal_curado', nombre: 'Idiazábal curado', categoria: 'do_curado', do_id: 'idiazabal', curacion_minima_dias: '120', descripcion: 'DO Idiazábal curación larga', revisado_por: ''),
    TipoQueso(id: 'idiazabal_ahumado', nombre: 'Idiazábal ahumado', categoria: 'do_curado', do_id: 'idiazabal', curacion_minima_dias: '60', descripcion: 'DO Idiazábal ahumado con haya/abedul/espino', revisado_por: ''),
    TipoQueso(id: 'manchego_semicurado', nombre: 'Manchego semicurado', categoria: 'do_curado', do_id: 'manchego', curacion_minima_dias: '30', descripcion: 'DO Manchego curación media', revisado_por: ''),
    TipoQueso(id: 'manchego_curado', nombre: 'Manchego curado', categoria: 'do_curado', do_id: 'manchego', curacion_minima_dias: '60', descripcion: 'DO Manchego curación prolongada', revisado_por: ''),
    TipoQueso(id: 'cabrales', nombre: 'Cabrales', categoria: 'do_azul', do_id: 'cabrales', curacion_minima_dias: '60', descripcion: 'Queso azul de Asturias en cueva natural', revisado_por: ''),
    TipoQueso(id: 'roncal', nombre: 'Roncal', categoria: 'do_curado', do_id: 'roncal', curacion_minima_dias: '120', descripcion: 'DO Roncal solo leche cruda de Latxa 4 meses mínimo', revisado_por: ''),
    TipoQueso(id: 'mahon_Menorca', nombre: 'Mahón-Menorca', categoria: 'do_curado', do_id: 'mahon', curacion_minima_dias: '60', descripcion: 'DO Mahón curado entre 60 y 150 días', revisado_por: ''),
    TipoQueso(id: 'torta_casar', nombre: 'Torta del Casar', categoria: 'do_blanda', do_id: 'torta_casar', curacion_minima_dias: '60', descripcion: 'DO Torta del Casar pasta blanda extremeña', revisado_por: ''),
    TipoQueso(id: 'zamorano', nombre: 'Zamorano', categoria: 'do_curado', do_id: 'zamorano', curacion_minima_dias: '100', descripcion: 'DO Zamorano mínimo 100 días de curación', revisado_por: ''),
    TipoQueso(id: 'tetilla', nombre: 'Tetilla', categoria: 'do_blanda', do_id: 'tetilla', curacion_minima_dias: '30', descripcion: 'DO Tetilla gallega forma cónica', revisado_por: ''),
    TipoQueso(id: 'arzua_ulloa', nombre: 'Arzúa-Ulloa', categoria: 'do_blanda', do_id: 'arzua_ulloa', curacion_minima_dias: '7', descripcion: 'DO Arzúa-Ulloa gallega pasta blanda', revisado_por: ''),
    TipoQueso(id: 'majorero', nombre: 'Majorero', categoria: 'do_curado', do_id: 'majorero', curacion_minima_dias: '30', descripcion: 'DO Majorero de Fuerteventura leche de cabra', revisado_por: ''),
    TipoQueso(id: 'azul', nombre: 'Azul artesano', categoria: 'azul', do_id: '', curacion_minima_dias: '60', descripcion: 'Queso azul sin DO', revisado_por: ''),
    TipoQueso(id: 'pasta_blanda', nombre: 'Pasta blanda artesano', categoria: 'blanda', do_id: '', curacion_minima_dias: '7', descripcion: 'Queso de pasta blanda genérico', revisado_por: ''),
    TipoQueso(id: 'pasta_dura', nombre: 'Pasta dura artesano', categoria: 'dura', do_id: '', curacion_minima_dias: '90', descripcion: 'Queso de pasta dura genérico', revisado_por: ''),
    TipoQueso(id: 'fresco_cabra', nombre: 'Fresco de cabra', categoria: 'fresco', do_id: '', curacion_minima_dias: '0', descripcion: 'Leche de cabra sin curar', revisado_por: ''),
    TipoQueso(id: 'fresco_mixto', nombre: 'Fresco mezcla', categoria: 'fresco', do_id: '', curacion_minima_dias: '0', descripcion: 'Mezcla de leches sin curar', revisado_por: ''),
    TipoQueso(id: 'ahumado', nombre: 'Ahumado artesano', categoria: 'ahumado', do_id: '', curacion_minima_dias: '30', descripcion: 'Queso ahumado con madera natural', revisado_por: ''),
];
