// dart run tool/compilar_traducciones.dart
// Lee content/solera/traducciones.csv y genera solera_l10n.dart
// con las 4 traducciones (es/eu/ca/gl).

import 'dart:convert';
import 'dart:io';

const _rutaCsv = '../../content/solera/traducciones.csv';
const _rutaSalida = '../../packages/nuevo_ser_core/lib/src/i18n/solera_l10n.dart';

void main() {
  final csvFile = File(_rutaCsv);
  if (!csvFile.existsSync()) {
    print('No encontrado: $_rutaCsv');
    exit(1);
  }

  final lineas = csvFile
      .readAsLinesSync()
      .where((l) => l.trim().isNotEmpty && !l.trim().startsWith('#'))
      .toList();

  if (lineas.length < 2) {
    print('CSV vacío o solo cabecera');
    exit(1);
  }

  final cabeceras = _parseCsvLine(lineas[0]);
  final filas = lineas.skip(1).map(_parseCsvLine).toList();

  // Mapear columnas
  final idxClave = cabeceras.indexOf('clave');
  final idxEs = cabeceras.indexOf('es');
  final idxEu = cabeceras.indexOf('eu');
  final idxCa = cabeceras.indexOf('ca');
  final idxGl = cabeceras.indexOf('gl');

  final codigo = StringBuffer();
  codigo.writeln("/// GENERATED FILE — DO NOT EDIT MANUALLY");
  codigo.writeln("/// Generated by tool/compilar_traducciones.dart from content/solera/traducciones.csv");
  codigo.writeln("/// Run 'dart run tool/compilar_traducciones.dart' to regenerate.");
  codigo.writeln();
  codigo.writeln("class SoleraL10n {");
  codigo.writeln("  SoleraL10n._();");
  codigo.writeln();
  codigo.writeln("  static String _idioma = 'es';");
  codigo.writeln("  static String get idioma => _idioma;");
  codigo.writeln("  static set idioma(String c) { _idioma = c; }");
  codigo.writeln();
  codigo.writeln("  static String t(String clave, {String? idioma}) {");
  codigo.writeln("    switch (idioma ?? _idioma) {");
  codigo.writeln("      case 'eu': return _tEu(clave);");
  codigo.writeln("      case 'ca': return _tCa(clave);");
  codigo.writeln("      case 'gl': return _tGl(clave);");
  codigo.writeln("      default: return _tEs(clave);");
  codigo.writeln("    }");
  codigo.writeln("  }");
  codigo.writeln();

  for (final [lang, fnName] in [
    ['es', '_tEs'],
    ['eu', '_tEu'],
    ['ca', '_tCa'],
    ['gl', '_tGl'],
  ]) {
    final idxLang = cabeceras.indexOf(lang);
    codigo.writeln("  static String $fnName(String c) {");
    codigo.writeln("    switch (c) {");

    for (final fila in filas) {
      final clave = fila[idxClave].trim();
      final texto = idxLang < fila.length ? fila[idxLang].trim() : '';
      if (texto.isEmpty) continue;
      codigo.writeln("      case '${_escapar(clave)}': return '${_escapar(texto)}';");
    }

    codigo.writeln("      default: return c;");
    codigo.writeln("    }");
    codigo.writeln("  }");
    codigo.writeln();
  }

  codigo.writeln("}");
  codigo.writeln();

  File(_rutaSalida).writeAsStringSync(codigo.toString());
  print('✅ solera_l10n.dart generado (${filas.length} claves x 4 idiomas)');
}

/// Escapa caracteres problemáticos para un literal Dart con comillas simples.
String _escapar(String s) {
  return s
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'")
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '')
      .replaceAll(r'$', r'\$');
}

List<String> _parseCsvLine(String linea) {
  final resultado = <String>[];
  bool enComillas = false;
  final buf = StringBuffer();
  for (int i = 0; i < linea.length; i++) {
    final c = linea[i];
    if (c == '"') {
      enComillas = !enComillas;
    } else if (c == ',' && !enComillas) {
      resultado.add(buf.toString().trim());
      buf.clear();
    } else {
      buf.write(c);
    }
  }
  resultado.add(buf.toString().trim());
  return resultado;
}
