// dart run tool/compilar_catalogos.dart
// Lee los 5 CSVs de content/quesera/ y genera 5 .dart en
// lib/datos/catalogos_generados/ + flag_revision.dart

import 'dart:io';

const _rutaContent = '../../content/quesera';
const _rutaSalida = 'lib/datos/catalogos_generados';

final _catalogos = [
  _Catalogo('tipos_queso', 'TipoQueso',
      ['id', 'nombre', 'categoria', 'do_id', 'curacion_minima_dias', 'descripcion']),
  _Catalogo('razas_lecheras', 'RazaLechera', [
    'id', 'nombre_comun', 'nombre_cientifico', 'tipo_leche',
    'zona_originaria', 'do_asociada',
  ]),
  _Catalogo('do_quesos', 'DoQueso', [
    'id', 'nombre', 'tipo', 'zona_geografica', 'razas_permitidas',
    'tipo_leche', 'coccion', 'curacion_minima_dias', 'ahumado_permitido',
    'organismo_control', 'web',
  ]),
  _Catalogo('defectos_queso', 'DefectoQueso', [
    'id', 'nombre', 'tipo', 'causa_posible', 'severidad',
    'requiere_accion', 'visible_ia',
  ]),
  _Catalogo('parametros_analitica', 'ParametroAnalitica', [
    'id', 'nombre', 'unidad', 'tipo', 'limite_legal', 'metodo',
  ]),
];

void main() {
  final outDir = Directory(_rutaSalida);
  if (!outDir.existsSync()) outDir.createSync(recursive: true);

  bool todosRevisados = true;

  for (final cat in _catalogos) {
    final csvPath = '$_rutaContent/${cat.archivo}.csv';
    final csvFile = File(csvPath);
    if (!csvFile.existsSync()) {
      print('⚠️  No encontrado: $csvPath');
      todosRevisados = false;
      continue;
    }

    final lineas = csvFile
        .readAsLinesSync()
        .where((l) => l.trim().isNotEmpty && !l.trim().startsWith('#'))
        .toList();

    if (lineas.length < 2) {
      print('⚠️  Vacío o solo cabecera: $csvPath');
      todosRevisados = false;
      continue;
    }

    final cabeceras = _parseCsvLine(lineas[0]);
    final filas = lineas.skip(1).map(_parseCsvLine).toList();

    // Comprobar revisión
    final idxRevisado = cabeceras.indexOf('revisado_por');
    if (idxRevisado >= 0) {
      for (final f in filas) {
        if (idxRevisado < f.length && f[idxRevisado].trim().isEmpty) {
          todosRevisados = false;
          break;
        }
      }
    }

    final registros = filas.map((f) {
      final map = <String, String>{};
      for (int i = 0; i < cabeceras.length && i < f.length; i++) {
        map[cabeceras[i]] = f[i].trim();
      }
      return map;
    }).toList();

    final dart = '''
// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by tool/compilar_catalogos.dart from content/quesera/${cat.archivo}.csv
// Run 'dart run tool/compilar_catalogos.dart' to regenerate.

class ${cat.clase} {
  ${registros.first.keys.map((k) => "final String $k;").join('\n  ')}

  const ${cat.clase}({
    ${registros.first.keys.map((k) => "required this.$k,").join('\n    ')}
  });

  factory ${cat.clase}.fromMap(Map<String, String> m) => ${cat.clase}(
    ${registros.first.keys.map((k) => "$k: m['$k'] ?? '',").join('\n    ')}
  );

  Map<String, String> toMap() => {
    ${registros.first.keys.map((k) => "'$k': $k,").join('\n    ')}
  };
}

const List<${cat.clase}> todos${cat.clase}s = [
  ${registros.map((r) {
    final args = r.keys.map((k) => "$k: '${r[k]?.replaceAll("'", "\\'") ?? ""}'");
    return '  ${cat.clase}(${args.join(', ')}),';
  }).join('\n  ')}
];
''';

    File('$_rutaSalida/${cat.archivo}.dart').writeAsStringSync(dart);
    print('✅ ${cat.archivo}.dart — ${registros.length} registros');
  }

  // Flag de revisión completa
  final flag = '''
// GENERATED FILE — DO NOT EDIT MANUALLY
const bool catalogosCompletamenteRevisados = $todosRevisados;
''';
  File('$_rutaSalida/flag_revision.dart').writeAsStringSync(flag);
  print(todosRevisados
      ? '✅ Todos los catálogos están revisados'
      : '⚠️  Hay catálogos con datos provisionales (revisado_por vacío)');
}

List<String> _parseCsvLine(String linea) {
  final resultado = <String>[];
  bool enComillas = false;
  final buf = StringBuffer();
  for (int i = 0; i < linea.length; i++) {
    final c = linea[i];
    if (c == '"') {
      enComillas = !enComillas;
    } else if (c == ',' && !enComillas) {
      resultado.add(buf.toString().trim());
      buf.clear();
    } else {
      buf.write(c);
    }
  }
  resultado.add(buf.toString().trim());
  return resultado;
}

class _Catalogo {
  final String archivo;
  final String clase;
  final List<String> cabecerasEsperadas;
  _Catalogo(this.archivo, this.clase, this.cabecerasEsperadas);
}
